import { list } from "@vercel/blob";
import { handleUpload, type HandleUploadBody } from "@vercel/blob/client";
import { NextResponse } from "next/server";
import {
  getAdminSessionFromCookieHeader,
  getAdminSessionFromUploadToken
} from "@/lib/admin-auth";

export const dynamic = "force-dynamic";
export const revalidate = 0;

async function getBlobTokenError() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  if (!token) {
    return "BLOB_READ_WRITE_TOKEN is missing. Connect a Vercel Blob store to this project, then redeploy.";
  }

  if (!token.startsWith("vercel_blob_rw_")) {
    return "BLOB_READ_WRITE_TOKEN is invalid. Use the read/write token generated by Vercel Blob.";
  }

  try {
    await list({ limit: 1, token });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown Vercel Blob error";

    return `BLOB_READ_WRITE_TOKEN cannot access a Vercel Blob store: ${message}`;
  }

  return null;
}

function jsonResponse(payload: Record<string, unknown>, status = 200) {
  return NextResponse.json(payload, {
    status,
    headers: {
      "Cache-Control": "no-store"
    }
  });
}

async function getAdminFromRequest(request: Request) {
  const cookieAdmin = await getAdminSessionFromCookieHeader(request.headers.get("cookie"));

  if (cookieAdmin) {
    return cookieAdmin;
  }

  return getAdminSessionFromUploadToken(getBearerToken(request));
}

function getBearerToken(request: Request) {
  const authorization = request.headers.get("authorization");

  if (!authorization?.startsWith("Bearer ")) {
    return null;
  }

  return authorization.slice("Bearer ".length).trim();
}

export async function GET(request: Request) {
  const hasCredential = Boolean(request.headers.get("cookie") || getBearerToken(request));
  const admin = await getAdminFromRequest(request);

  if (!admin) {
    return jsonResponse(
      {
        error: hasCredential
          ? "Admin upload access is invalid or expired. Refresh the admin page, then retry."
          : "Admin upload access was not sent. Sign in at /admin/login on this same domain, then retry."
      },
      401
    );
  }

  const tokenError = await getBlobTokenError();

  if (tokenError) {
    return jsonResponse({ error: tokenError }, 500);
  }

  return jsonResponse({ ready: true, admin: admin.email });
}

export async function POST(request: Request) {
  const body = (await request.json()) as HandleUploadBody;

  try {
    const tokenError = await getBlobTokenError();

    if (tokenError) {
      throw new Error(tokenError);
    }

    const response = await handleUpload({
      body,
      request,
      onBeforeGenerateToken: async () => {
        const admin = await getAdminFromRequest(request);

        if (!admin) {
          throw new Error("Admin login required.");
        }

        return {
          allowedContentTypes: ["application/pdf", "image/jpeg", "image/png", "image/webp"],
          addRandomSuffix: true,
          callbackUrl: new URL(request.url).toString(),
          tokenPayload: JSON.stringify({
            adminId: admin.id
          })
        };
      },
      onUploadCompleted: async ({ blob }) => {
        console.log("BookBridge blob upload completed", blob.url);
      }
    });

    return jsonResponse(response);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Upload failed.";

    return jsonResponse({ error: message }, 400);
  }
}
