import { handleUpload, type HandleUploadBody } from "@vercel/blob/client";
import { NextResponse } from "next/server";
import { getAdminSession } from "@/lib/admin-auth";

function getBlobTokenError() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;

  if (!token) {
    return "BLOB_READ_WRITE_TOKEN is missing. Connect a Vercel Blob store to this project, then redeploy.";
  }

  if (!token.startsWith("vercel_blob_rw_")) {
    return "BLOB_READ_WRITE_TOKEN is invalid. Use the read/write token generated by Vercel Blob.";
  }

  return null;
}

export async function GET() {
  const admin = await getAdminSession();

  if (!admin) {
    return NextResponse.json({ error: "Admin login required." }, { status: 401 });
  }

  const tokenError = getBlobTokenError();

  if (tokenError) {
    return NextResponse.json({ error: tokenError }, { status: 500 });
  }

  return NextResponse.json({ ready: true });
}

export async function POST(request: Request) {
  const body = (await request.json()) as HandleUploadBody;

  try {
    const tokenError = getBlobTokenError();

    if (tokenError) {
      throw new Error(tokenError);
    }

    const response = await handleUpload({
      body,
      request,
      onBeforeGenerateToken: async () => {
        const admin = await getAdminSession();

        if (!admin) {
          throw new Error("Admin login required.");
        }

        return {
          allowedContentTypes: ["application/pdf", "image/jpeg", "image/png", "image/webp"],
          addRandomSuffix: true,
          tokenPayload: JSON.stringify({
            adminId: admin.id
          })
        };
      },
      onUploadCompleted: async ({ blob }) => {
        console.log("BookBridge blob upload completed", blob.url);
      }
    });

    return NextResponse.json(response);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Upload failed.";

    return NextResponse.json({ error: message }, { status: 400 });
  }
}
